name: web_directorio
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.

version: 1.0.0+1

environment:
  sdk: ^3.2.0

# Dependencies specify other packages that your package needs in order to work.

dependencies:
  flutter:
    sdk: flutter

  google_fonts: 
  cupertino_icons: ^1.0.2
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  firebase_auth: ^6.1.1
  image_picker: ^1.0.4
  http: ^1.6.0
  url_launcher: ^6.2.2

dev_dependencies:

  change_app_package_name: ^1.5.0
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  
  uses-material-design: true
  assets:
   - assets/

  # To add assets to your application, add an assets section, like this:
  